name: Build
on: [push]
jobs:
  native:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: ./make-debian

      - name: Upload ${{ env.MACHINE_EMULATOR_TOOLS_TAR }}
        uses: actions/upload-artifact@v3
        with:
          name: genext2fs.deb
          path: genext2fs.deb

  release:
    name: Release machine emulator tarball
    needs: [native]
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download
        uses: actions/download-artifact@master
        with:
          name: genext2fs.deb
          path: genext2fs.deb

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: genext2fs.deb
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
